### ISSUE TITLE
import page object do page object?

### ISSUE THREAD

**Issue by DanielLipowicz** [mkrzesinski/LevelUP2017JS#1]
https://github.com/mkrzesinski/LevelUP2017JS/blob/50ad043239eae19b46421694f1db6fb0abdec63d/pageObject/homePage.js#L9

```
var HomePage = function HomePage(){
    this.URL = 'http://automationpractice.com/index.php';
    this.cartLabel = element(By.css('.shopping_cart'));
    this.contactUsLink = element(By.css('#contact-link'));
    this.womanButton = element(By.css('a[title=\'Women\']'));
    this.dressesButton = element(By.css('#block_top_menu > ul > li:nth-child(2) > a'))
}
module.exports = HomePage;
var HomePage = require(pageObjectDir+"/homePage.js");
var homePage = new HomePage();
var WomenPage = require(pageObjectDir+"/womenPage.js");
var womenPage = new WomenPage();
```

Nie musisz importować HomePage do HomePage. Ten obiekt jest juz tu dostępny.

womenPage też nie powinno być w tym page objectie. Jeśli masz jakąś akcje do wykonania stwórz metodę w womanPage.

**Comment by mkrzesinski** [comment]
Rzeczywiście, te rzeczy były niepotrzebne, chyba przez nieuwagę je zostawiłem. Już poprawione.

**Comment by DanielLipowicz** [comment]
Dobra robota. Zamykam oba problemy.
